import type { Metadata } from "next";
import "_styles/globals.css";
import { Children, Params } from "_types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Children;
export default function RootLayout(props: Props) {
  return props.children;
}
