import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "_styles/globals.css";
import { Children, Params } from "_types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "fa" }, { lang: "en" }];
}

type Props = Children & Params;
export default function RootLayout(props: Props) {
  const { children, params } = props;

  return (
    <html lang={params.lang} dir={params.lang === "fa" ? "rtl" : "ltr"}>
      <body
        className={params.lang === "fa" ? "font-dana font-light" : "font-marko"}
      >
        {children}
      </body>
    </html>
  );
}
