import type { Metadata } from "next";
import "_styles/globals.css";
import { Children, Params } from "_types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Children & Params;
export default function LangLayout(props: Props) {
  const { children, params } = props;

  return (
    <html lang={params.lang} dir={params.lang === "fa" ? "rtl" : "ltr"}>
      <body
        className={params.lang === "fa" ? "font-dana font-light" : "font-marko"}
      >
        {children}
      </body>
    </html>
  );
}
